server:
  port: 8081

## URL Rest Services applicacion
coins:
  baseURL: 'api/coins'
  healthAPI: '/health-api'
  urlAssertPlatform: '/assetPlatforms'

## Url Coin Gecko RestService
api:
  urlCoinGecko: 'https://api.coingecko.com/api/v3'
  ping: '/ping'
  urlAssertPlatform: '/asset_platforms'
